-- MySQL Script generated by MySQL Workbench
-- Mon Aug  8 12:06:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema simpreserv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simpreserv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simpreserv` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `simpreserv` ;

-- -----------------------------------------------------
-- Table `simpreserv`.`payment_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`payment_types` (
  `payment_type_id` INT NOT NULL AUTO_INCREMENT,
  `payment_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`clients` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `doc_number` VARCHAR(10) NULL DEFAULT NULL,
  `email` VARCHAR(25) NULL DEFAULT NULL,
  `enabled` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`positions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`positions` (
  `position_id` INT NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(45) NULL DEFAULT NULL,
  `position_salary` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`shifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`shifts` (
  `shift_id` INT NOT NULL AUTO_INCREMENT,
  `shift_name` VARCHAR(20) NULL DEFAULT NULL,
  `hour_start` TIME NULL DEFAULT NULL,
  `hour_end` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`shift_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `carnet` VARCHAR(25) NULL DEFAULT NULL,
  `enabled` TINYINT NULL DEFAULT NULL,
  `POSITIONS_position_id` INT NOT NULL,
  `SHIFTS_shift_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `carnet_UNIQUE` (`carnet` ASC) VISIBLE,
  INDEX `fk_EMPLOYEES_POSITIONS1_idx` (`POSITIONS_position_id` ASC) VISIBLE,
  INDEX `fk_EMPLOYEES_SHIFTS1_idx` (`SHIFTS_shift_id` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYEES_POSITIONS1`
    FOREIGN KEY (`POSITIONS_position_id`)
    REFERENCES `simpreserv`.`positions` (`position_id`),
  CONSTRAINT `fk_EMPLOYEES_SHIFTS1`
    FOREIGN KEY (`SHIFTS_shift_id`)
    REFERENCES `simpreserv`.`shifts` (`shift_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`rooms` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NULL DEFAULT NULL,
  `floor` INT NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `room_price` DECIMAL(10,0) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `available` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`reservation_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`reservation_status` (
  `reservation_status_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`reservation_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`reservations` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `reservation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `checkin_date` DATE NULL DEFAULT NULL,
  `checkout_date` DATE NULL DEFAULT NULL,
  `reservation_balance` DECIMAL(10,0) NULL DEFAULT NULL,
  `EMPLOYEE_employee_id` INT NOT NULL,
  `CLIENT_client_id` INT NOT NULL,
  `ROOM_room_id` INT NOT NULL,
  `RESERVATION_STATUS_reservation_status_id` INT NOT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `fk_RESERVATION_EMPLOYEE1_idx` (`EMPLOYEE_employee_id` ASC) VISIBLE,
  INDEX `fk_RESERVATION_CLIENT1_idx` (`CLIENT_client_id` ASC) VISIBLE,
  INDEX `fk_RESERVATION_ROOM1_idx` (`ROOM_room_id` ASC) VISIBLE,
  INDEX `fk_RESERVATIONS_RESERVATION_STATUS1_idx` (`RESERVATION_STATUS_reservation_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVATION_CLIENT1`
    FOREIGN KEY (`CLIENT_client_id`)
    REFERENCES `simpreserv`.`clients` (`client_id`),
  CONSTRAINT `fk_RESERVATION_EMPLOYEE1`
    FOREIGN KEY (`EMPLOYEE_employee_id`)
    REFERENCES `simpreserv`.`employees` (`employee_id`),
  CONSTRAINT `fk_RESERVATION_ROOM1`
    FOREIGN KEY (`ROOM_room_id`)
    REFERENCES `simpreserv`.`rooms` (`room_id`),
  CONSTRAINT `fk_RESERVATIONS_RESERVATION_STATUS1`
    FOREIGN KEY (`RESERVATION_STATUS_reservation_status_id`)
    REFERENCES `simpreserv`.`reservation_status` (`reservation_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `payment_number` VARCHAR(45) NULL DEFAULT NULL,
  `amount` DECIMAL(10,0) NULL DEFAULT NULL,
  `PAYMENT_TYPE_payment_type_id` INT NOT NULL,
  `RESERVATIONS_reservation_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `fk_PAYMENT_PAYMENT_TYPE1_idx` (`PAYMENT_TYPE_payment_type_id` ASC) VISIBLE,
  INDEX `fk_PAYMENTS_RESERVATIONS1_idx` (`RESERVATIONS_reservation_id` ASC) VISIBLE,
  CONSTRAINT `fk_PAYMENT_PAYMENT_TYPE1`
    FOREIGN KEY (`PAYMENT_TYPE_payment_type_id`)
    REFERENCES `simpreserv`.`payment_types` (`payment_type_id`),
  CONSTRAINT `fk_PAYMENTS_RESERVATIONS1`
    FOREIGN KEY (`RESERVATIONS_reservation_id`)
    REFERENCES `simpreserv`.`reservations` (`reservation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`cash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`cash` (
  `cash_id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cash_taken` DECIMAL(10,0) NULL DEFAULT NULL,
  `cash_given` DECIMAL(10,0) NULL DEFAULT NULL,
  `PAYMENTS_payment_id` INT NOT NULL,
  PRIMARY KEY (`cash_id`),
  INDEX `fk_table1_PAYMENTS1_idx` (`PAYMENTS_payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_PAYMENTS1`
    FOREIGN KEY (`PAYMENTS_payment_id`)
    REFERENCES `simpreserv`.`payments` (`payment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`check` (
  `check_id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `check_number` VARCHAR(30) NULL DEFAULT NULL,
  `check_reference` VARCHAR(25) NULL DEFAULT NULL,
  `PAYMENTS_payment_id` INT NOT NULL,
  PRIMARY KEY (`check_id`),
  INDEX `fk_CHECK_PAYMENTS1_idx` (`PAYMENTS_payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_CHECK_PAYMENTS1`
    FOREIGN KEY (`PAYMENTS_payment_id`)
    REFERENCES `simpreserv`.`payments` (`payment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`creditcard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`creditcard` (
  `creditcard_id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `creditcard_number` VARCHAR(4) NULL DEFAULT NULL,
  `creditcard_exp_month` VARCHAR(2) NULL DEFAULT NULL,
  `creditcard_exp_year` VARCHAR(2) NULL DEFAULT NULL,
  `creditcard_authorization` VARCHAR(20) NULL DEFAULT NULL,
  `PAYMENTS_payment_id` INT NOT NULL,
  PRIMARY KEY (`creditcard_id`),
  INDEX `fk_CREDITCARD_PAYMENTS1_idx` (`PAYMENTS_payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_CREDITCARD_PAYMENTS1`
    FOREIGN KEY (`PAYMENTS_payment_id`)
    REFERENCES `simpreserv`.`payments` (`payment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`user_types` (
  `user_type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`user_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `simpreserv`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simpreserv`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL,
  `email` VARCHAR(30) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `enabled` TINYINT NULL DEFAULT NULL,
  `EMPLOYEES_employee_id` INT NOT NULL,
  `USER_TYPES_user_type_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_USERS_EMPLOYEES1_idx` (`EMPLOYEES_employee_id` ASC) VISIBLE,
  INDEX `fk_USERS_USER_TYPES1_idx` (`USER_TYPES_user_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_USERS_EMPLOYEES1`
    FOREIGN KEY (`EMPLOYEES_employee_id`)
    REFERENCES `simpreserv`.`employees` (`employee_id`),
  CONSTRAINT `fk_USERS_USER_TYPES1`
    FOREIGN KEY (`USER_TYPES_user_type_id`)
    REFERENCES `simpreserv`.`user_types` (`user_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
